# Generated by Django 5.1.6 on 2025-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
    ]
